### ISSUE TITLE
日志解析报错

### ISSUE THREAD

**Issue by DDstrongman** [Meituan-Dianping/Logan#129]
decrypt complete
remove padding complete
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17) errno: -5, code: 'Z_BUF_ERROR' }

start decode log file
decrypt complete
remove padding complete
write finish

start decode log file
decrypt complete
remove padding complete
write finish

start decode log file
decrypt complete
internal/buffer.js:47
    throw new ERR_BUFFER_OUT_OF_BOUNDS();
    ^

RangeError [ERR_BUFFER_OUT_OF_BOUNDS]: Attempt to write outside buffer bounds
    at boundsError (internal/buffer.js:47:11)
    at Buffer.readUInt8 (internal/buffer.js:137:5)
    at decodeLog (/data/app/Logan/Example/Logan-Server/server.js:81:32)
    at decodeLog (/data/app/Logan/Example/Logan-Server/server.js:120:7)
    at WriteStream.inp.pipe.on.pipe.on (/data/app/Logan/Example/Logan-Server/server.js:114:11)
    at WriteStream.emit (events.js:203:15)
    at finishMaybe (_stream_writable.js:646:14)
    at stream._final (_stream_writable.js:624:5)
    at WriteStream._final (internal/fs/streams.js:268:3)
    at callFinal (_stream_writable.js:617:10)

**Comment by DDstrongman** [comment]
日志无截断，应该是直接少了一块数据。

**Comment by DDstrongman** [comment]
目前解析了几十万条日志，只遇到这一块问题。9月之前都么的人力重写server.js，只能求助大腿们了

**Comment by Richard-Cao** [comment]
这个问题没遇到过哎，是最新的server.js代码吗？

**Comment by DDstrongman** [comment]
是最新的server.js,也和姜同学反馈过了。

**Comment by DDstrongman** [comment]
补充一发报错信息
start decode log file
decrypt complete
remove padding complete
outputFilename is  10887431_2019-08-27-15-38-46_1-6-0_12-4_iPhone9-2_17B48A49-EC2A-40A5-857E-0940F75454CC
{ Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17) errno: -3, code: 'Z_DATA_ERROR' }
start is 0
skips is:  1420
start is 1
skips is:  1421

**Comment by Richard-Cao** [comment]
iOS还是Android？

**Comment by DDstrongman** [comment]
iOS

**Comment by DDstrongman** [comment]
这个是后端解析报错，还哪端有关联么- -

**Comment by Richard-Cao** [comment]
腾哥在继续跟进这个问题

**Comment by jiangteng** [comment]
美团生产环境用的是java版本解析，python只是个模板样例，方便的话推荐使用java版本后端解析。

**Comment by DDstrongman** [comment]
了该，我再试试java

**Comment by DDstrongman** [comment]
java.parse也是同样的报错啊。。老哥。。。

**Comment by DDstrongman** [comment]
我看到有同学提了issue贴出来了，我这边也是这个报错信息。

**Comment by DDstrongman** [comment]
看报错信息应该是和server.js同一个报错原因

**Comment by wuqifeng** [comment]
我也遇到了相同的问题, node

**Comment by Richard-Cao** [comment]
> 我也遇到了相同的问题, node

最新版的？

**Comment by zikobe** [comment]
`Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:168:17) {
  errno: -3,
  code: 'Z_DATA_ERROR'
}`

**Comment by zikobe** [comment]
我也遇到node解析报错，不知道大佬们解决了没

**Comment by ShiminChen007** [comment]
> 美团生产环境用的是java版本解析，python只是个模板样例，方便的话推荐使用java版本后端解析。

是否可以提供一下Java解析的模板呀，我尝试了解析一直报错javax.crypto.IllegalBlockSizeException: error:1e06b07b:Cipher functions:EVP_DecryptFinal_ex:WRONG_FINAL_BLOCK_LENGTH

**Comment by GaoYuJian** [comment]
node 用下面的方法解密，和java的实现一样，用内置的zlib会报错需要用pako

```js
import { AES, enc, mode, pad, format } from 'crypto-js'
import { ungzip } from 'pako'

/**
   * 解密一段日志
   * @param buffer
   */
  decryptContent(buffer: Buffer): Buffer {
    const result = AES.decrypt(
      buffer.toString('hex'),
      enc.Utf8.parse(AES_KEY),
      {
        iv: enc.Utf8.parse(IV),
        mode: mode.CBC,
        padding: pad.NoPadding,
        format: format.Hex,
      },
    ).toString(enc.Hex)
    const resultBuf = Buffer.from(result, 'hex')

    return resultBuf
  }

  /**
   * 解压日志
   * @param buffer
   */
  async decompressContent(buffer: Buffer): Promise<string> {
    const content = ungzip(buffer)
    return Buffer.from(content).toString()
  }
}

```

**Comment by lixiao123** [comment]
https://github.com/lixiao123/DeLogan

**Comment by daizhenhong** [comment]
decompressContent这个方法报错 incorrect header check

**Comment by netfishx** [comment]
decompressContent这个方法报错 incorrect header check
有解决办法吗
