### ISSUE TITLE
测试上传日志文件的时候报错了，接收到了部分日志信息，求解

### ISSUE THREAD

**Issue by kevin1202** [Meituan-Dianping/Logan#26]
测试上传日志文件的时候报错了，接收到了部分日志信息，求解
```
{ Error: unexpected end of file
    at Zlib.zlibOnError [as onerror] (zlib.js:153:17) errno: -5, code: 'Z_BUF_ERROR' }
write finish
fs.js:113
    throw err;
    ^

Error: ENOENT: no such file or directory, unlink './log-demo.gz'
    at Object.unlinkSync (fs.js:916:3)
    at WriteStream.inp.pipe.on.pipe.on (/Users/yangkai/development/git/Logan/Example/Logan-Server/server.js:113:14)
    at WriteStream.emit (events.js:187:15)
    at finishMaybe (_stream_writable.js:641:14)
    at stream._final (_stream_writable.js:619:5)
    at WriteStream._final (internal/fs/streams.js:264:3)
    at callFinal (_stream_writable.js:612:10)
    at process._tickCallback (internal/process/next_tick.js:63:19)
```

**Comment by Richard-Cao** [comment]
具体操作是怎么样的？

**Comment by kevin1202** [comment]
Logan.s(temp, mSendLogRunnable); temp数组有最近4天的日志，写入日志，然后点击上传，目前本地日志有最近三天的

**Comment by Richard-Cao** [comment]
用demo测试的？

**Comment by kevin1202** [comment]
是的，有demo测试的

**Comment by Richard-Cao** [comment]
接受到的部分日志是哪部分？

**Comment by kevin1202** [comment]
是最近两天的，目前这个日志信息被我毁了，昨天测试的，开始是23号的日志，结束的时候，24的日志，22的日志没有看到，貌似日志文件大一些 就会出现问题

**Comment by Richard-Cao** [comment]
日志不全么

**Comment by Richard-Cao** [comment]
压缩是流式的，有终止符，缺少终止符，会有一小段字节解析失败。进程被杀导致压缩不完整，最后一个json 数据解析失败。
可以在APP前后台切换或者Crash时flush，以防数据丢失。
