### ISSUE TITLE
旧版LoganParser.java解码问题

### ISSUE THREAD

**Issue by aaasss112** [Meituan-Dianping/Logan#261]
最近Android客户端升级到版本1.2.4，用原来LoganParser.java写的解码有很多用户出现java.util.zip.ZipException: Not in GZIP format
        at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
        at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
        at com.company.LoganParser.parse(LoganParser.java:97)
        at com.company.Main.lambda$main$0(Main.java:32)
        at java.lang.Thread.run(Thread.java:748)
这是要更新解码方式了吗，是否有对应的java解码代码。

**Comment by Richard-Cao** [comment]
开源的server就是最新的
