### ISSUE TITLE
启动 server.js报错  node 版本为 4.4.3   npm 版本 2.15.1

### ISSUE THREAD

**Issue by daixiansen** [Meituan-Dianping/Logan#30]
D:\demo\Logan\Example\Logan-Server> node server.js
D:\demo\Logan\Example\Logan-Server\server.js:83
      let padding = 0;
      ^^^

SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
    at exports.runInThisContext (vm.js:53:16)
    at Module._compile (module.js:373:25)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
    at startup (node.js:139:18)
    at node.js:968:3

**Comment by Richard-Cao** [comment]
升级一下node版本到6以上试试
