### ISSUE TITLE
CLoganProtocol解析数据丢失

### ISSUE THREAD

**Issue by rigortek** [Meituan-Dianping/Logan#324]
恢复之前的某个版本，拿到了log解析类：
https://github.com/rigortek/Logan/blob/master/Example/Logan-Android/logan/src/main/java/com/dianping/logan/CLoganProtocol.java

连续写入了900条数据
```
private void loganTest() {
        new Thread() {
            @Override
            public void run() {
                super.run();
                try {
                    for (int i = 0; i < 900; i++) {
                        Log.d(TAG, "times : " + i);
                        Logan.w(processName + " " + i, 1);
                        Thread.sleep(50);
                    }
                    Log.d(TAG, "write log end");
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
                Logan.f();
            }
        }.start();
    }
```
processName是包名test.logan.dianping.com.logan，
发现从第3条数据到第315条数据丢失，每次必现，而且我在最后是调用了flush的。

```
{"c":"clogan header","f":1,"l":1609842952121,"n":"clogan","i":1,"m":true}
{"c":"test.logan.dianping.com.logan MyApplication onCreate","f":3,"l":1609842952111,"n":"main","i":1,"m":true}
{"c":"test.logan.dianping.com.logan MyApplication onCreate","f":3,"l":1609842952111,"n":"main","i":1,"m":true}
{"c":"test.logan.dianping.com.logan MyApplication onCreate","f":3,"l":1609842952111,"n":"main","i":1,"m":true}
{"c":"test.logan.dianping.com.logan 0","f":1,"l":1609842952225,"n":"Thread-544","i":544,"m":false}
{"c":"test.logan.dianping.com.logan 1","f":1,"l":16098429522{"c":"test.logan.dianping.com.logan 313","f":1,"l":1609842968014,"n":"Thread-544","i":544,"m":false}
{"c":"test.logan.dianping.com.logan 314","f":1,"l":1609842968065,"n":"Thread-544","i":544,"m":false}
...
{"c":"test.logan.dianping.com.logan 899","f":1,"l":1609842968418,"n":"Thread-544","i":544,"m":false}

```

**Comment by Richard-Cao** [comment]
用demo也有这个情况？这问题曾经有人问过，最后发现是使用不当导致的。

**Comment by rigortek** [comment]
> 用demo也有这个情况？这问题曾经有人问过，最后发现是使用不当导致的。

**Comment by rigortek** [comment]
> 用demo也有这个情况？这问题曾经有人问过，最后发现是使用不当导致的。

demo没有此问题，我进行了一项目配置调整，但是代码只有少量调整，
目前发现运行启动后，提示jacoco warning，还不清楚是否是此导致的。
`E/Environment( 1148): canonicalPath = /storage/sdcard
W/System.err( 1148): java.io.FileNotFoundException: /jacoco.exec: open failed: EROFS (Read-only file system)
W/System.err( 1148):    at libcore.io.IoBridge.open(IoBridge.java:456)
W/System.err( 1148):    at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
W/System.err( 1148):    at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.openFile(FileOutput.java:67)
W/System.err( 1148):    at org.jacoco.agent.rt.internal_8ff85ea.output.FileOutput.startup(FileOutput.java:49)
W/System.err( 1148):    at org.jacoco.agent.rt.internal_8ff85ea.Agent.startup(Agent.java:122)
W/System.err( 1148):    at org.jacoco.agent.rt.internal_8ff85ea.Agent.getInstance(Agent.java:50)
W/System.err( 1148):    at org.jacoco.agent.rt.internal_8ff85ea.Offline.<clinit>(Offline.java:31)
W/System.err( 1148):    at com.dianping.logan.LoganConfig$Builder.$jacocoInit(LoganConfig.java)
W/System.err( 1148):    at com.dianping.logan.LoganConfig$Builder.<init>(LoganConfig.java)
W/System.err( 1148):    at test.logan.dianping.com.logan.MyApplication.initLogan(MyApplication.java:34)
W/System.err( 1148):    at test.logan.dianping.com.logan.MyApplication.onCreate(MyApplication.java:26)
W/System.err( 1148):    at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1012)
W/System.err( 1148):    at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4566)
W/System.err( 1148):    at android.app.ActivityThread.access$1500(ActivityThread.java:151)
W/System.err( 1148):    at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1364)
W/System.err( 1148):    at android.os.Handler.dispatchMessage(Handler.java:102)
W/System.err( 1148):    at android.os.Looper.loop(Looper.java:135)
W/System.err( 1148):    at android.app.ActivityThread.main(ActivityThread.java:5267)
W/System.err( 1148):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 1148):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 1148):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 1148):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/System.err( 1148): Caused by: android.system.ErrnoException: open failed: EROFS (Read-only file system)
W/System.err( 1148):    at libcore.io.Posix.open(Native Method)
W/System.err( 1148):    at libcore.io.BlockGuardOs.open(BlockGuardOs.java:186)
W/System.err( 1148):    at libcore.io.IoBridge.open(IoBridge.java:442)
W/System.err( 1148):    ... 21 more
`

**Comment by rigortek** [comment]
@Richard-Cao 经过回退代码及反复验证，目前可以确定诱发此问题的原因是，开启了多进程
(我在Logan-Android基础上增加一个单独进程的Service)
如果两个进程共享一份MyApplication中的LoganConfig配置代码，就会必现此问题。

请问Logan对一个APK多进程支持情况如何？对LoganConfig配置有什么要求么？

**Comment by Richard-Cao** [comment]
目前还没兼容多进程……

> @Richard-Cao 经过回退代码及反复验证，目前可以确定诱发此问题的原因是，开启了多进程
> (我在Logan-Android基础上增加一个单独进程的Service)
> 如果两个进程共享一份MyApplication中的LoganConfig配置代码，就会必现此问题。
> 
> 请问Logan对一个APK多进程支持情况如何？对LoganConfig配置有什么要求么？

**Comment by rigortek** [comment]
> 目前还没兼容多进程……
> 
> > @Richard-Cao 经过回退代码及反复验证，目前可以确定诱发此问题的原因是，开启了多进程
> > (我在Logan-Android基础上增加一个单独进程的Service)
> > 如果两个进程共享一份MyApplication中的LoganConfig配置代码，就会必现此问题。
> > 请问Logan对一个APK多进程支持情况如何？对LoganConfig配置有什么要求么？

刚看了一下美团手机客户端APK，里面大量组件都配置了android:process="xxx"，使用了独立进程，
不可能这个APK没有使用logan吧？
翻了一下前面bug，有几个人反馈数据解析失败，我推测可能部分问题是多进程引发的。

通过不同进程使用不同cache path/target path方式实现进程隔离，能否实现多进程支持？
当然能在ndk层实现多进程支持最好了。

**Comment by Richard-Cao** [comment]
> > 目前还没兼容多进程……
> > > @Richard-Cao 经过回退代码及反复验证，目前可以确定诱发此问题的原因是，开启了多进程
> > > (我在Logan-Android基础上增加一个单独进程的Service)
> > > 如果两个进程共享一份MyApplication中的LoganConfig配置代码，就会必现此问题。
> > > 请问Logan对一个APK多进程支持情况如何？对LoganConfig配置有什么要求么？
> 
> 刚看了一下美团手机客户端APK，里面大量组件都配置了android:process="xxx"，使用了独立进程，
> 不可能这个APK没有使用logan吧？
> 翻了一下前面bug，有几个人反馈数据解析失败，我推测可能部分问题是多进程引发的。
> 
> 通过不同进程使用不同cache path/target path方式实现进程隔离，能否实现多进程支持？
> 当然能在ndk层实现多进程支持最好了。

其实最好的方式还是在logan内层支持下。美团的其他进程大多不是主业务的，比如推送的 webview之类的，Logan主要还是用做个案分析的，主进程基本就cover了。多进程支持这个我反馈下

**Comment by rigortek** [comment]
> > > 目前还没兼容多进程……
> > > > @Richard-Cao 经过回退代码及反复验证，目前可以确定诱发此问题的原因是，开启了多进程
> > > > (我在Logan-Android基础上增加一个单独进程的Service)
> > > > 如果两个进程共享一份MyApplication中的LoganConfig配置代码，就会必现此问题。
> > > > 请问Logan对一个APK多进程支持情况如何？对LoganConfig配置有什么要求么？
> > 
> > 
> > 刚看了一下美团手机客户端APK，里面大量组件都配置了android:process="xxx"，使用了独立进程，
> > 不可能这个APK没有使用logan吧？
> > 翻了一下前面bug，有几个人反馈数据解析失败，我推测可能部分问题是多进程引发的。
> > 通过不同进程使用不同cache path/target path方式实现进程隔离，能否实现多进程支持？
> > 当然能在ndk层实现多进程支持最好了。
> 
> 其实最好的方式还是在logan内层支持下。美团的其他进程大多不是主业务的，比如推送的 webview之类的，Logan主要还是用做个案分析的，主进程基本就cover了。多进程支持这个我反馈下

请问有支持计划么？现在的单个APP多个多进程，而且各进程中业务都很重要，不支持多进程的限制太大，盼实现，多谢。

**Comment by lijheng** [comment]
> > 目前还没兼容多进程……
> > > @Richard-Cao 经过回退代码及反复验证，目前可以确定诱发此问题的原因是，开启了多进程
> > > (我在Logan-Android基础上增加一个单独进程的Service)
> > > 如果两个进程共享一份MyApplication中的LoganConfig配置代码，就会必现此问题。
> > > 请问Logan对一个APK多进程支持情况如何？对LoganConfig配置有什么要求么？
> 
> 刚看了一下美团手机客户端APK，里面大量组件都配置了android:process="xxx"，使用了独立进程， 不可能这个APK没有使用logan吧？ 翻了一下前面bug，有几个人反馈数据解析失败，我推测可能部分问题是多进程引发的。
> 
> 通过不同进程使用不同cache path/target path方式实现进程隔离，能否实现多进程支持？ 当然能在ndk层实现多进程支持最好了。

您好，我也考虑使用不同进程不同cache path/target path的方案，但是考虑到抓取日志一般是在主进程，上传日志前需要调用一次Logan.f()操作日志全部被写入，请问您这边是怎么处理的呢
