### ISSUE TITLE
用LoganParser-java来解密解压报错

### ISSUE THREAD

**Issue by RenZhongrui** [Meituan-Dianping/Logan#35]
java.util.zip.ZipException: Not in GZIP format
	at java.util.zip.GZIPInputStream.readHeader(GZIPInputStream.java:165)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:79)
	at java.util.zip.GZIPInputStream.<init>(GZIPInputStream.java:91)
	at cn.com.agree.LoganParser.parse(LoganParser.java:95)
	at cn.com.agree.Test.main(Test.java:18)

**Comment by jiangteng** [comment]
这是正常情况。因为一些特殊情况会报解压异常，不影响整体解析。解析后的日志log-demo.txt数据正常即可。

**Comment by leonardocsc** [comment]
我也遇到解析异常的情况，但是异常信息和上面不一样。。。异常信息如下：
`java.io.EOFException: Unexpected end of ZLIB input stream
       	at java.util.zip.InflaterInputStream.fill(InflaterInputStream.java:240)
       	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
       	at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:117)
       	at java.io.FilterInputStream.read(FilterInputStream.java:107)`

**Comment by Richard-Cao** [comment]
@leonardocsc 能解析出日志吗

**Comment by leonardocsc** [comment]
一般能解析成功。但是偶会解析不出来。
