### ISSUE TITLE
提供一个python解密日志的脚本

### ISSUE THREAD

**Issue by madaoCN** [Meituan-Dianping/Logan#351]
```
#!/usr/bin/env python
#coding=utf8

import gzip
try:
    from cStringIO import StringIO
except:
    from StringIO import StringIO
import codecs
import struct
# pip install PyCrypto
from Crypto.Cipher import AES
from optparse import OptionParser

def logan_parse(infile, dst, key, iv):
    '''
    logan 文件解密
    :param infile: 输入文件
    :param dst: 输出文件地址
    :return: NULL
    '''
    dst = open(dst, 'w+')
    with codecs.open(infile, mode='rb') as file:
        # 读取1个字节
        while(file.read(1) == '\x01'):
            # 读取四个字节, 转成int(大端)
            bts = file.read(4)
            print ("four bytes: ", [bts])
            size = struct.unpack('>I', bts)[0]
            print ("size: ", size)

            # 读取加密内容
            encrypted_content = file.read(size)
            print ("encrypted_content: ", [encrypted_content])
            # des 解密
            aes_decryptor = AES.new(key, AES.MODE_CBC, iv)
            decrypted = aes_decryptor.decrypt(encrypted_content)
            print("decrypted_content: ", [decrypted])

            # 读取压缩内容
            compressed_content = decrypted

            # 获取最后一个字节
            last_byte = compressed_content[-1]
            padding_length = struct.unpack('>b', last_byte)[0]
            print ("padding_len: ", padding_length)

            # 截取padding之前字节
            compressed_content = compressed_content[0:-padding_length]
            # print ("compressed_content: ", [compressed_content])

            # 解压
            tempIO = StringIO(compressed_content)
            unGzipIO = gzip.GzipFile(mode = 'rb', fileobj=tempIO)
            decompressed = unGzipIO.read()

            # 写入文件
            print (decompressed)
            dst.write(decompressed)

            # 最后读一个尾巴
            tail = file.read(1)

if __name__ == "__main__":
    arg_parser = OptionParser(
        usage="usage: %prog -i input_path [-o output_path] -k key -v iv"
    )
    arg_parser.add_option("-i", "--input",
                          action="store",
                          type="string",
                          help="input file path")
    arg_parser.add_option("-o", "--output",
                          action="store",
                          type="string",
                          help="output file path")
    arg_parser.add_option("-k", "--key",
                          action="store",
                          type="string",
                          help="aes key")
    arg_parser.add_option("-v", "--iv",
                          action="store",
                          type="string",
                          help="aes iv")
    (options, args) = arg_parser.parse_args()
    
    input_path = options.input
    key = options.key
    iv = options.iv

    if not input_path or not key or not iv:
        arg_parser.print_help()
        exit(0)

    output_path = options.output
    if not options.output:
        output_path = input_path
        output_path += "_decompressed.txt"

    # 执行解析
    logan_parse(input_path, output_path, key, iv)
```

**Comment by Richard-Cao** [comment]
棒棒

**Comment by madaoCN** [comment]
(*^▽^*)

**Comment by CherryLover** [comment]
好像不能用呢？输出的文件内容是空的，而且执行过程中没有任何输出

**Comment by madaoCN** [comment]
> 好像不能用呢？输出的文件内容是空的，而且执行过程中没有任何输出

没有输出可能是logan_parse没有进去，检查下脚本调用的参数

**Comment by CherryLover** [comment]
非常谢谢你的回复，不过我当时参考他的 Server 项目中的 Protocol 类重写了一个 Java 版本的，可惜某些日志文件还是会出现解析失败的问题，应该是 Logan 日志生成时的问题，后面我把这个 Server 项目跑起来，然后通过 postman 发起请求，同样也是会报错。

**Comment by madaoCN** [comment]
> otocol 类重写了一个 Java 版本的，可惜某些日志文件还是会出现解析失败的问题，应该是 Logan 日志生成时的问题，后面我把这

这个脚本自己也是在使用中，倒是没有出现解析失败类似问题，你可以再提个 issue 问问咋回事哈

**Comment by CherryLover** [comment]
你那边是 iOS 端上传的日志吗？我是 Android 端上传的日志会有概率出现解析失败的问题

**Comment by madaoCN** [comment]
> 你那边是 iOS 端上传的日志吗？我是 Android 端上传的日志会有概率出现解析失败的问题

是的，的确是 iOS 端上传的

**Comment by zhangxi28** [comment]
这个脚本解析文件一部分后报错。不能完全解析。部分日志如下：

adj\xe9\xf2\x14\xf0\xf0?z<h\x10\xf6\x06&\xa1\xc1FR\x99\x13H\xe2\xc8\xfc\x9fM^\xb6gxy9K\xe7\xd3U\xba\xb0<s\xd0\x8d\x81\xad\x8a/\xa6\xe7\xd3\x0c\xdd\xa3\x0e*P\x82;h\xfb`n?\xee aN?}\xd3\x88\xe6\xfc\xa7\x89\xae\xeb\x1a>\xde'])
('last_byte: ', '\xde')
('padding_len: ', -34)
('compressed_content: ', ['\x1f\x8b\x08\x00\x00\x00\x00\x00\x02\x03\x8cR\xcd\x8e\xd30\x10\xbe\xf3\x14\x91\xcf%u\xd2\xfc\xb4\xb9u\xdb.t\xa1\xcd'])
Traceback (most recent call last):
  File "test1.py", line 112, in <module>
    logan_parse(input_path, output_path, key, iv)
  File "test1.py", line 63, in logan_parse
    decompressed = unGzipIO.read()
  File "D:\programs\python2\lib\gzip.py", line 260, in read
    self._read(readsize)
  File "D:\programs\python2\lib\gzip.py", line 314, in _read
    self._read_eof()
  File "D:\programs\python2\lib\gzip.py", line 353, in _read_eof
    hex(self.crc)))
IOError: CRC check failed 0xdb75b9b4L != 0x0L


请问这个怎么改？

**Comment by MakeForce** [comment]
参考@madaoCN 的Python版，写了一个 Nodejs的解密：[https://gist.github.com/MakeForce/8a15ee64bae84bc751c7c43cd6ac15ba](https://gist.github.com/MakeForce/8a15ee64bae84bc751c7c43cd6ac15ba)
注：如果日志解析失败的，大概率是  #320 同样的问题

**Comment by kbjay** [comment]
@zhangxi28 请教下，这个问题解决了吗

**Comment by ArmsZhou** [comment]
```python
import gzip
import io
import codecs
import struct
from Crypto.Cipher import AES


def logan_parse(infile, dst, key, iv):
    """
    logan 文件解密
    :param iv: aes key
    :param key: aes iv
    :param infile: 输入文件
    :param dst: 输出文件地址
    :return: NULL
    """
    with open(dst, 'wb') as dst:
        with codecs.open(infile, mode='rb') as file:
            # 读取1个字节
            while file.read(1) == b'\x01':
                # 读取四个字节, 转成int(大端)
                bts = file.read(4)
                print("four bytes: ", [bts])
                size = struct.unpack('>I', bts)[0]
                print("size: ", size)

                # 读取加密内容
                encrypted_content = file.read(size)
                print("encrypted_content: ", [encrypted_content])
                # aes 解密
                aes_decrypt = AES.new(key, AES.MODE_CBC, iv)
                decrypted = aes_decrypt.decrypt(encrypted_content)
                print("decrypted_content: ", [decrypted])

                # 读取压缩内容
                compressed_content = decrypted

                # 获取最后一个字节
                # '>b' 只能表示 -127-128 的有符号证书，'>B' 可以表示 0-255
                # 这里可能会得到 255 的整数值
                last_byte = compressed_content[-1]
                byte_val = struct.pack('>B', last_byte)
                padding_length = struct.unpack('>B', byte_val)[0]
                print("padding_len: ", padding_length)

                # 截取padding之前字节
                compressed_content = compressed_content[0:-padding_length]
                # print ("compressed_content: ", [compressed_content])

                # 解压
                # 会出现解压失败的情况，直接跳过这段数据
                try:
                    temp_io = io.BytesIO(compressed_content)
                    un_gzip_io = gzip.GzipFile(mode='rb', fileobj=temp_io)
                    decompressed = un_gzip_io.read()
                    # 写入文件
                    # print("decompressed_content: ", decompressed)
                    dst.write(decompressed)
                except Exception as e:
                    print("解压失败，错误信息：", e)
                    continue

                # 只有存在填充时，才读一个尾巴
                if padding_length != 0:
                    tail = file.read(1)
                    print("tail:", tail)
```

代码修改后已经可以解密出完整日志。

**Comment by leolovenet** [comment]
提供一个支持 `AES.MODE_CTR` 格式的版本

```python
#!/usr/bin/env python3
#coding=utf8

import io
import sys
import gzip
import struct
from Crypto.Cipher import AES # pip3 install -U pycryptodome
from optparse import OptionParser

def logan_parse(file, dst, key, iv, mode="CBC"):
    with open(file, mode='rb') as file:
        while file.read(1) == b'\x01':
            bts = file.read(4)
            size = struct.unpack('>I', bts)[0]

            encrypted_content = file.read(size)

            if mode == "CTR":
                cipher = AES.new(key, AES.MODE_CTR, nonce=iv[:8], initial_value=int.from_bytes(iv[8:], byteorder='big'))
            else:
                cipher = AES.new(key, AES.MODE_CBC, iv)

            decrypted_content = cipher.decrypt(encrypted_content)
            compressed_content = decrypted_content

            # 获取最后一个字节
            # '>b' 只能表示 -127-128 的有符号证书，'>B' 可以表示 0-255
            # 这里可能会得到 255 的整数值
            last_byte = compressed_content[-1]
            byte_val = struct.pack('>B', last_byte)
            padding_length = struct.unpack('>B', byte_val)[0]
            # print("padding_len: ", padding_length)

            compressed_content = compressed_content[0:-padding_length]

            try:
                with io.BytesIO(compressed_content) as temp_io:
                    with gzip.GzipFile(fileobj=temp_io, mode='rb') as un_gzip_io:
                        decompressed = un_gzip_io.read()
                        if dst:
                            with open(dst, 'ab') as dst_file:
                                dst_file.write(decompressed)
                        else:
                            print(decompressed.decode('utf-8', errors='replace'))
            except Exception as e:
                print(f"解压失败，错误信息：{e}", file=sys.stderr)
                continue

            if padding_length != 0:
                tail = file.read(1)
                # print(f"tail: {tail.hex()}", file=sys.stderr)

if __name__ == "__main__":
    arg_parser = OptionParser(
        usage="usage: %prog -f input_path [-o output_path] -k key -i iv"
    )
    arg_parser.add_option("-f", "--input",
                          action="store",
                          type="string",
                          help="input file path")
    arg_parser.add_option("-o", "--output",
                          action="store",
                          type="string",
                          help="output file path")
    arg_parser.add_option("-k", "--key",
                          action="store",
                          type="string",
                          help="aes key")
    arg_parser.add_option("-i", "--iv",
                          action="store",
                          type="string",
                          help="aes iv")
    arg_parser.add_option("-m", "--mode",
                          action="store",
                          type="string",
                          help="aes mode, CBC(default) or CTR",
                          default="CBC")
    (options, args) = arg_parser.parse_args()

    input_path = options.input
    output_path = options.output
    key = options.key
    iv = options.iv
    mode = options.mode

    if not input_path or not key or not iv:
        arg_parser.print_help()
        exit(0)

    if len(key) != 16 or len(iv) != 16:
        print("错误: Key 和 IV 的长度必须是 16 字节")
        exit(1)

    if mode not in ["CBC", "CTR"]:
        print("错误: 只支持 CBC 或 CTR 模式")
        exit(1)

    logan_parse(input_path, output_path, key.encode(), iv.encode(), mode=mode)

```
