### ISSUE TITLE
Android 端问题

### ISSUE THREAD

**Issue by gxh-apologize** [Meituan-Dianping/Logan#514]
1、下载的Demol运行的，点击了“测试Logan默认上报方式”，报如下错误，是测试地址关了吗？
`IOException : java.net.UnknownHostException: Unable to resolve host "openlogan.inf.test.sankuai.com": No address associated with hostname
2024-04-25 17:20:44.607 28397-28512 System.err              pid-28397                            W  	at com.dianping.logan.SendLogDefaultRunnable.doPostRequest(SendLogDefaultRunnable.java:138)
2024-04-25 17:20:44.607 28397-28512 System.err              pid-28397                            W  	at com.dianping.logan.SendLogDefaultRunnable.doSendFileByAction(SendLogDefaultRunnable.java:104)
2024-04-25 17:20:44.607 28397-28512 System.err              pid-28397                            W  	at com.dianping.logan.SendLogDefaultRunnable.sendLog(SendLogDefaultRunnable.java:60)`

2、我们自己部署了后端，“测试Logan默认上报方式”的方法里直接改了下接口地址，报错：
`{
	"code": 500,
	"msg": "ERROR_DATABASE",
	"data": null
}`

这个大概是什么引起的呢？iOS没问题。

3、请问有群吗？求拉。

**Comment by wsxyeah** [comment]
后端需要自己部署，2看起来是写入数据库失败了可以查下错误日志
