### ISSUE TITLE
前端构建时失败

### ISSUE THREAD

**Issue by allegrox** [Meituan-Dianping/Logan#525]
试了1.2 .8和1.2.11

=> ERROR [frontend frontend 4/4] RUN yarn config set registry https://registry.npmmirror.com -g &&     yarn config set sass_binary_site "https  55.4s
------                                                                                                                                                 
 > [frontend frontend 4/4] RUN yarn config set registry https://registry.npmmirror.com -g &&     yarn config set sass_binary_site "https://npmmirror.com/mirrors/node-sass/" -g  &&     yarn &&     yarn build:                                                                                               
0.269 yarn config v1.22.5                                                                                                                              
0.291 success Set "registry" to "https://registry.npmmirror.com".                                                                                      
0.292 Done in 0.03s.                                                                                                                                   
0.440 yarn config v1.22.5
0.467 success Set "sass_binary_site" to "https://npmmirror.com/mirrors/node-sass/".
0.467 Done in 0.03s.
0.617 yarn install v1.22.5
0.642 info No lockfile found.
0.647 [1/4] Resolving packages...
1.457 warning @svgr/webpack > @svgr/plugin-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
2.005 warning @svgr/webpack > @svgr/plugin-svgo > svgo > stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
2.256 warning @svgr/webpack > @svgr/plugin-svgo > svgo > coa > q@1.5.1: You or someone you depend on is using Q, the JavaScript Promise library that gave JavaScript developers strong feelings about promises. They can almost certainly migrate to the native JavaScript promise now. Thank you literally everyone for joining me in this bet against the odds. Be excellent to each other.
2.256 
2.256 (For a CapTP with native promises, see @endo/eventual-send and @endo/captp)
3.767 warning @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > glob@7.2.3: Glob versions prior to v9 are no longer supported
3.803 warning @typescript-eslint/eslint-plugin > @typescript-eslint/experimental-utils > @typescript-eslint/typescript-estree > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
4.737 warning antd > babel-runtime > core-js@2.6.12: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
4.910 warning antd > rc-editor-mention > draft-js > fbjs > core-js@1.2.7: core-js@<3.23.3 is no longer maintained and not recommended for usage due to the number of issues. Because of the V8 engine whims, feature detection in old core-js versions could cause a slowdown up to 100x even if nothing is polyfilled. Some versions have web compatibility issues. Please, upgrade your dependencies to the actual version of core-js.
5.130 warning axios@0.19.2: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
5.201 warning babel-eslint@10.0.3: babel-eslint is now @babel/eslint-parser. This package will no longer receive updates.
5.333 warning babel-jest > babel-plugin-istanbul > test-exclude > glob@7.2.3: Glob versions prior to v9 are no longer supported
5.519 warning babel-jest > @jest/transform > jest-haste-map > sane@4.1.0: some dependency vulnerabilities fixed, support for node < 10 dropped, and newer ECMAScript syntax/features added
5.522 warning babel-jest > @jest/transform > jest-haste-map > fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
5.629 warning babel-jest > @jest/transform > micromatch > snapdragon > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
5.781 warning babel-jest > @jest/transform > micromatch > snapdragon > source-map-resolve > resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
5.788 warning babel-jest > @jest/transform > micromatch > snapdragon > source-map-resolve > source-map-url@0.4.1: See https://github.com/lydell/source-map-url#deprecated
5.793 warning babel-jest > @jest/transform > micromatch > snapdragon > source-map-resolve > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
6.258 warning babel-preset-react-app > @babel/plugin-proposal-class-properties@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
6.260 warning babel-preset-react-app > @babel/plugin-proposal-nullish-coalescing-operator@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
6.261 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
6.264 warning babel-preset-react-app > @babel/plugin-proposal-optional-chaining@7.9.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
6.264 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
6.275 warning babel-preset-react-app > @babel/plugin-proposal-numeric-separator@7.8.3: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
6.275 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
6.301 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-dynamic-import@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-dynamic-import instead.
6.306 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-json-strings@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-json-strings instead.
6.313 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
6.313 warning babel-preset-react-app > @babel/preset-env > @babel/preset-modules > @babel/plugin-proposal-unicode-property-regex@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-unicode-property-regex instead.
6.325 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
6.356 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
6.371 warning babel-preset-react-app > @babel/preset-env > @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
7.311 warning eslint > file-entry-cache > flat-cache > rimraf@2.6.3: Rimraf versions prior to v4 are no longer supported
7.311 warning eslint > file-entry-cache > flat-cache > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
7.514 warning eslint-loader@3.0.2: This loader has been deprecated. Please use eslint-webpack-plugin
8.618 warning html-webpack-plugin@4.0.0-beta.5: please switch to a stable version
9.151 warning jest > jest-cli > jest-config > glob@7.2.3: Glob versions prior to v9 are no longer supported
9.173 warning jest > jest-cli > @jest/core > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
9.178 warning jest > jest-cli > @jest/core > rimraf > glob@7.2.3: Glob versions prior to v9 are no longer supported
9.254 warning jest > jest-cli > @jest/core > @jest/reporters > glob@7.2.3: Glob versions prior to v9 are no longer supported
9.291 warning jest > jest-cli > @jest/core > jest-runtime > glob@7.2.3: Glob versions prior to v9 are no longer supported
9.369 warning jest > jest-cli > @jest/core > @jest/reporters > istanbul-lib-source-maps > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
9.425 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
9.449 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > data-urls > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
9.452 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > domexception@1.0.1: Use your platform's native DOMException instead
9.459 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > left-pad@1.3.0: use String.prototype.padStart()
9.485 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
9.492 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
9.498 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
9.599 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > har-validator@5.1.5: this library is no longer supported
9.641 warning jest > jest-cli > jest-config > jest-environment-jsdom > jsdom > request > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
9.827 warning jest-environment-jsdom-fourteen > jsdom > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
9.828 warning jest-environment-jsdom-fourteen > jsdom > domexception@1.0.1: Use your platform's native DOMException instead
9.828 warning jest-environment-jsdom-fourteen > jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
9.828 warning jest-environment-jsdom-fourteen > jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
9.828 warning jest-environment-jsdom-fourteen > jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
9.862 warning jest-environment-jsdom-fourteen > jsdom > w3c-xmlserializer > domexception@1.0.1: Use your platform's native DOMException instead
10.52 warning optimize-css-assets-webpack-plugin > cssnano > cssnano-preset-default > postcss-svgo > svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
11.44 warning postcss-preset-env > postcss-color-gray > postcss-values-parser > flatten@1.0.3: flatten is deprecated in favor of utility frameworks such as lodash.
11.79 warning react-dev-utils > globby > glob@7.2.3: Glob versions prior to v9 are no longer supported
11.88 warning react-dev-utils > fork-ts-checker-webpack-plugin > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
11.88 warning react-dev-utils > fork-ts-checker-webpack-plugin > chokidar > fsevents@1.2.13: The v1 package contains DANGEROUS / INSECURE binaries. Upgrade to safe fsevents v2
13.12 warning redux-devtools-extension@2.13.9: Package moved to @redux-devtools/extension.
13.47 warning resolve-url-loader > rework > css > source-map-resolve@0.5.3: See https://github.com/lydell/source-map-resolve#deprecated
13.47 warning resolve-url-loader > rework > css > urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
13.80 warning terser-webpack-plugin > cacache > glob@7.2.3: Glob versions prior to v9 are no longer supported
13.80 warning terser-webpack-plugin > cacache > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
13.84 warning terser-webpack-plugin > cacache > move-concurrently@1.0.1: This package is no longer supported.
13.84 warning terser-webpack-plugin > cacache > move-concurrently > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
13.84 warning terser-webpack-plugin > cacache > figgy-pudding@3.5.2: This module is no longer supported.
13.87 warning terser-webpack-plugin > cacache > ssri > figgy-pudding@3.5.2: This module is no longer supported.
13.91 warning terser-webpack-plugin > cacache > move-concurrently > copy-concurrently@1.0.5: This package is no longer supported.
13.91 warning terser-webpack-plugin > cacache > move-concurrently > copy-concurrently > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
13.91 warning terser-webpack-plugin > cacache > move-concurrently > fs-write-stream-atomic@1.0.10: This package is no longer supported.
13.91 warning terser-webpack-plugin > cacache > move-concurrently > copy-concurrently > fs-write-stream-atomic@1.0.10: This package is no longer supported.
14.34 warning webpack > watchpack > watchpack-chokidar2 > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
14.64 warning webpack-dev-server > chokidar@2.1.8: Chokidar 2 does not receive security updates since 2019. Upgrade to chokidar 3 with 15x fewer dependencies
14.68 warning webpack-dev-server > del > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
14.68 warning webpack-dev-server > del > globby > glob@7.2.3: Glob versions prior to v9 are no longer supported
14.75 warning webpack-dev-server > sockjs > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
14.76 warning webpack-dev-server > webpack-log > uuid@3.4.0: Please upgrade  to version 7 or higher.  Older versions may use Math.random() in certain circumstances, which is known to be problematic.  See https://v8.dev/blog/math-random for details.
15.31 warning workbox-webpack-plugin > workbox-build > glob@7.2.3: Glob versions prior to v9 are no longer supported
15.34 warning workbox-webpack-plugin > workbox-build > @hapi/joi@15.1.1: Switch to 'npm install joi'
15.41 warning workbox-webpack-plugin > workbox-build > workbox-google-analytics@4.3.1: It is not compatible with newer versions of GA starting with v4, as long as you are using GAv3 it should be ok, but the package is not longer being maintained
15.45 warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/address@2.1.4: Moved to 'npm install @sideway/address'
15.48 warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
15.48 warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo@3.1.6: This version has been deprecated and is no longer supported or maintained
15.48 warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/topo > @hapi/hoek@8.5.1: This version has been deprecated and is no longer supported or maintained
15.49 warning workbox-webpack-plugin > workbox-build > @hapi/joi > @hapi/bourne@1.3.2: This version has been deprecated and is no longer supported or maintained
15.97 warning enzyme-adapter-react-16 > enzyme-adapter-utils > airbnb-prop-types@2.16.0: This package has been renamed to 'prop-types-tools'
16.09 warning jsdom > abab@2.0.6: Use your platform's native atob() and btoa() methods instead
16.09 warning jsdom > domexception@1.0.1: Use your platform's native DOMException instead
16.09 warning jsdom > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
16.09 warning jsdom > request-promise-native@1.0.9: request-promise-native has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
16.09 warning jsdom > w3c-hr-time@1.0.2: Use your platform's native performance.now() and performance.timeOrigin.
16.13 warning node-sass@4.14.1: Node Sass is no longer supported. Please use `sass` or `sass-embedded` instead.
16.13 warning node-sass > glob@7.2.3: Glob versions prior to v9 are no longer supported
16.13 warning node-sass > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
16.18 warning node-sass > npmlog@4.1.2: This package is no longer supported.
16.19 warning node-sass > node-gyp > glob@7.2.3: Glob versions prior to v9 are no longer supported
16.19 warning node-sass > node-gyp > npmlog@4.1.2: This package is no longer supported.
16.19 warning node-sass > node-gyp > request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
16.19 warning node-sass > node-gyp > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
16.20 warning node-sass > true-case-path > glob@7.2.3: Glob versions prior to v9 are no longer supported
16.22 warning node-sass > sass-graph > glob@7.2.3: Glob versions prior to v9 are no longer supported
16.25 warning node-sass > npmlog > are-we-there-yet@1.1.7: This package is no longer supported.
16.26 warning node-sass > npmlog > gauge@2.7.4: This package is no longer supported.
16.27 warning node-sass > node-gyp > fstream@1.0.12: This package is no longer supported.
16.27 warning node-sass > node-gyp > fstream > rimraf@2.7.1: Rimraf versions prior to v4 are no longer supported
16.28 warning node-sass > node-gyp > osenv@0.1.5: This package is no longer supported.
16.29 warning node-sass > node-gyp > tar@2.2.2: This version of tar is no longer supported, and will not receive security updates. Please upgrade asap.
16.29 warning node-sass > node-gyp > tar > fstream@1.0.12: This package is no longer supported.
16.32 warning node-sass > gaze > globule > glob@7.1.7: Glob versions prior to v9 are no longer supported
16.32 warning node-sass > gaze > globule > glob > inflight@1.0.6: This module is not supported, and leaks memory. Do not use it. Check out lru-cache if you want a good and tested way to coalesce async requests by a key value, which is much more comprehensive and powerful.
16.52 warning sinon@7.5.0: 16.1.1
16.70 [2/4] Fetching packages...
49.31 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
49.31 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
49.32 info fsevents@2.3.3: The platform "linux" is incompatible with this module.
49.32 info "fsevents@2.3.3" is an optional dependency and failed compatibility check. Excluding it from installation.
49.32 error cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "10.24.1"
49.32 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
49.32 error Found incompatible module.
------
failed to solve: process "/bin/sh -c yarn config set registry https://registry.npmmirror.com -g &&     yarn config set sass_binary_site \"https://npmmirror.com/mirrors/node-sass/\" -g  &&     yarn &&     yarn build" did not complete successfully: exit code: 1

**Comment by Richard-Cao** [comment]
是一些库的版本太老了？

**Comment by leozhang007** [comment]
同样的问题

**Comment by thisdk** [comment]
同样的问题

**Comment by leozhang007** [comment]
159.2 [2/4] Fetching packages...
193.8 info There appears to be trouble with your network connection. Retrying...
222.0 info There appears to be trouble with your network connection. Retrying...
285.7 info fsevents@1.2.13: The platform "linux" is incompatible with this module.
285.7 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation.
285.8 info fsevents@2.3.3: The platform "linux" is incompatible with this module.
285.8 info "fsevents@2.3.3" is an optional dependency and failed compatibility check. Excluding it from installation.
285.8 error cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "10.24.1"
285.8 error Found incompatible module.
285.8 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

看这个报错是 「cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "10.24.1"」
是不是容器的 node 版本太低了？

**Comment by leozhang007** [comment]
> 159.2 [2/4] Fetching packages... 193.8 info There appears to be trouble with your network connection. Retrying... 222.0 info There appears to be trouble with your network connection. Retrying... 285.7 info fsevents@1.2.13: The platform "linux" is incompatible with this module. 285.7 info "fsevents@1.2.13" is an optional dependency and failed compatibility check. Excluding it from installation. 285.8 info fsevents@2.3.3: The platform "linux" is incompatible with this module. 285.8 info "fsevents@2.3.3" is an optional dependency and failed compatibility check. Excluding it from installation. 285.8 error cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "10.24.1" 285.8 error Found incompatible module. 285.8 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> 
> 看这个报错是 「cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "10.24.1"」 是不是容器的 node 版本太低了？

尝试修改 node 版本，有了新的报错
FROM node:18-alpine as frontend
FROM node:20-alpine as frontend
这两个都报错找不到 python，报错如下：

1531.8 error /web/node_modules/node-sass: Command failed.
1531.8 Exit code: 1
1531.8 Command: node scripts/build.js
1531.8 Arguments: 
1531.8 Directory: /web/node_modules/node-sass
1531.8 Output:
1531.8 Building: /usr/local/bin/node /web/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
1531.8 gyp info it worked if it ends with ok
1531.8 gyp verb cli [
1531.8 gyp verb cli   '/usr/local/bin/node',
1531.8 gyp verb cli   '/web/node_modules/node-gyp/bin/node-gyp.js',
1531.8 gyp verb cli   'rebuild',
1531.8 gyp verb cli   '--verbose',
1531.8 gyp verb cli   '--libsass_ext=',
1531.8 gyp verb cli   '--libsass_cflags=',
1531.8 gyp verb cli   '--libsass_ldflags=',
1531.8 gyp verb cli   '--libsass_library='
1531.8 gyp verb cli ]
1531.8 gyp info using node-gyp@3.8.0
1531.8 gyp info using node@20.16.0 | linux | arm64
1531.8 gyp verb command rebuild []
1531.8 gyp verb command clean []
1531.8 gyp verb clean removing "build" directory
1531.8 gyp verb command configure []
1531.8 gyp verb check python checking for Python executable "python2" in the PATH
1531.8 gyp verb `which` failed Error: not found: python2
1531.8 gyp verb `which` failed     at getNotFoundError (/web/node_modules/which/which.js:13:12)
1531.8 gyp verb `which` failed     at F (/web/node_modules/which/which.js:68:19)
1531.8 gyp verb `which` failed     at E (/web/node_modules/which/which.js:80:29)
1531.8 gyp verb `which` failed     at /web/node_modules/which/which.js:89:16
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/index.js:42:5
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/mode.js:8:5
1531.8 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21)
1531.8 gyp verb `which` failed  python2 Error: not found: python2
1531.8 gyp verb `which` failed     at getNotFoundError (/web/node_modules/which/which.js:13:12)
1531.8 gyp verb `which` failed     at F (/web/node_modules/which/which.js:68:19)
1531.8 gyp verb `which` failed     at E (/web/node_modules/which/which.js:80:29)
1531.8 gyp verb `which` failed     at /web/node_modules/which/which.js:89:16
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/index.js:42:5
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/mode.js:8:5
1531.8 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21) {
1531.8 gyp verb `which` failed   code: 'ENOENT'
1531.8 gyp verb `which` failed }
1531.8 gyp verb check python checking for Python executable "python" in the PATH
1531.8 gyp verb `which` failed Error: not found: python
1531.8 gyp verb `which` failed     at getNotFoundError (/web/node_modules/which/which.js:13:12)
1531.8 gyp verb `which` failed     at F (/web/node_modules/which/which.js:68:19)
1531.8 gyp verb `which` failed     at E (/web/node_modules/which/which.js:80:29)
1531.8 gyp verb `which` failed     at /web/node_modules/which/which.js:89:16
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/index.js:42:5
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/mode.js:8:5
1531.8 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21)
1531.8 gyp verb `which` failed  python Error: not found: python
1531.8 gyp verb `which` failed     at getNotFoundError (/web/node_modules/which/which.js:13:12)
1531.8 gyp verb `which` failed     at F (/web/node_modules/which/which.js:68:19)
1531.8 gyp verb `which` failed     at E (/web/node_modules/which/which.js:80:29)
1531.8 gyp verb `which` failed     at /web/node_modules/which/which.js:89:16
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/index.js:42:5
1531.8 gyp verb `which` failed     at /web/node_modules/isexe/mode.js:8:5
1531.8 gyp verb `which` failed     at FSReqCallback.oncomplete (node:fs:197:21) {
1531.8 gyp verb `which` failed   code: 'ENOENT'
1531.8 gyp verb `which` failed }
1531.8 gyp ERR! configure error 
1531.8 gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
1531.8 gyp ERR! stack     at PythonFinder.failNoPython (/web/node_modules/node-gyp/lib/configure.js:484:19)
1531.8 gyp ERR! stack     at PythonFinder.<anonymous> (/web/node_modules/node-gyp/lib/configure.js:406:16)
1531.8 gyp ERR! stack     at F (/web/node_modules/which/which.js:68:16)
1531.8 gyp ERR! stack     at E (/web/node_modules/which/which.js:80:29)
1531.8 gyp ERR! stack     at /web/node_modules/which/which.js:89:16
1531.8 gyp ERR! stack     at /web/node_modules/isexe/index.js:42:5
1531.8 gyp ERR! stack     at /web/node_modules/isexe/mode.js:8:5
1531.8 gyp ERR! stack     at FSReqCallback.oncomplete (node:fs:197:21)
1531.8 gyp ERR! System Linux 6.10.0-linuxkit
1531.8 gyp ERR! command "/usr/local/bin/node" "/web/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
1531.8 gyp ERR! cwd /web/node_modules/node-sass
1531.8 gyp ERR! node -v v20.16.0
1531.8 gyp ERR! node-gyp -v v3.8.0
1531.8 gyp ERR! not ok 
1531.8 Build failed with error code: 1
1531.8 info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
------
failed to solve: process "/bin/sh -c yarn config set registry https://registry.npmmirror.com -g &&     yarn config set sass_binary_site \"https://npmmirror.com/mirrors/node-sass/\" -g  &&     yarn &&     yarn build" did not complete successfully: exit code: 1

**Comment by GaryChangCN** [comment]
1. 删除 node_modules、package-lock.json、yarn.lock  文件
2. 使用 node v10.24.1 版本，npm 版本使用 v6.14.2  （不可以大于 v7）
3. 重新使用 npm 安装依赖  npm i 同时建议使用国内源避免 node-sass 编译耗时  （ npm i --registry=https://registry.npmmirror.com）
5. 重新运行，验证正常启动   npm run start
6. 重新 npm run build

**Comment by GaryChangCN** [comment]
用这个分支验证下
https://github.com/Meituan-Dianping/Logan/tree/bugfix/website-toolchain-fix

**Comment by zhangchenglong0830** [comment]
![d7296a18-98a8-4bca-b244-acd61defec50](https://github.com/user-attachments/assets/59842f32-4fb7-4a54-bc89-07bf407030e0)
同样的报错，😂

**Comment by williamhqs** [comment]
日志里很清楚 期望>=18.17, 现在是10.24.1. 使用node:18-alpine试试
