### ISSUE TITLE
invalid block type

### ISSUE THREAD

**Issue by yilingfeixian** [Meituan-Dianping/Logan#82]
2019-03-13 16:09:26.580 20250-20250/com.example.logdemo W/System.err: java.util.zip.ZipException: invalid block type
2019-03-13 16:09:26.580 20250-20250/com.example.logdemo W/System.err:     at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:170)
2019-03-13 16:09:26.580 20250-20250/com.example.logdemo W/System.err:     at java.util.zip.GZIPInputStream.read(GZIPInputStream.java:115)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at java.io.FilterInputStream.read(FilterInputStream.java:107)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at com.example.logdemo.LoganParser.parse(LoganParser.java:77)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at com.example.logdemo.MainActivity$1.onClick(MainActivity.java:61)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at android.view.View.performClick(View.java:5647)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at android.view.View$PerformClick.run(View.java:22465)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at android.os.Handler.handleCallback(Handler.java:754)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:95)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at android.os.Looper.loop(Looper.java:163)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6389)
2019-03-13 16:09:26.581 20250-20250/com.example.logdemo W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
2019-03-13 16:09:26.582 20250-20250/com.example.logdemo W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:901)
2019-03-13 16:09:26.582 20250-20250/com.example.logdemo W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:791)

**Comment by Richard-Cao** [comment]
你把解析日志的代码集成在Android里了？

**Comment by yilingfeixian** [comment]
> 你把解析日志的代码集成在Android里了？

对啊，有问题吗？

**Comment by yilingfeixian** [comment]
> 你把解析日志的代码集成在Android里了？
如果不把代码放安卓里，那该如何解析

**Comment by Richard-Cao** [comment]
日志上传到后端，由后端进行解析……不是在APP里解析的

**Comment by yilingfeixian** [comment]
> 日志上传到后端，由后端进行解析……不是在APP里解析的

后端解析和安卓李解析有区别吗？后端解析你说的时用node.js吗？

**Comment by Richard-Cao** [comment]
后端你用什么解析都可以，因为上传前会进行flush操作，可以看下Logan相关的文章和使用场景
